### YamlMime:UniversalReference
ms.openlocfilehash: 0d455cabfa21cf1f23f41044b06af8adc3bb21a3
ms.sourcegitcommit: 286f52ea38c9eff2ec9d4f8cabeb86f62fd9c406
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/22/2018
ms.locfileid: "41682455"
items:
- uid: azure-iot-common.ArgumentError
  name: ArgumentError
  fullName: ArgumentError
  children:
  - azure-iot-common.ArgumentError.constructor
  - azure-iot-common.ArgumentError.Error
  langs:
  - typeScript
  type: class
  summary: 인수가 유효 하지 않을 때 발생 하는 데 오류가 발생 했습니다.
  extends:
    name: Error
  package: azure-iot-common
- uid: azure-iot-common.ArgumentError.constructor
  name: ArgumentError
  children: []
  type: constructor
  langs:
  - typeScript
  summary: ''
  syntax:
    content: 'new ArgumentError(message?: string)'
    parameters:
    - id: message
      type:
      - string
      description: ''
      optional: true
  package: azure-iot-common
- uid: azure-iot-common.ArgumentError.Error
  name: Error
  fullName: Error
  children: []
  langs:
  - typeScript
  type: property
  summary: ''
  syntax:
    content: 'static Error: ErrorConstructor'
    return:
      type:
      - ErrorConstructor
  package: azure-iot-common
